<?php

/**
 * @file
 * Module implementation for Views Attachments as Tabs Olivero.
 */

use Drupal\Component\Utility\Html;

/**
 * Implements hook_preprocess_HOOK() for views_view_attachment_tabs.
 */
function views_attachment_tabs_olivero_preprocess_views_view_attachment_tabs(array &$variables) {
  if (!_views_attachment_tabs_olivero_theme_is_activated()) {
    return;
  }

  /** @var \Drupal\views\ViewExecutable $view */
  $view = $variables['view'];
  $view_id = $view->id();

  // Enable wrapping the tab navigations list into a nav tab.
  $variables['wrap_tab_navigations'] = TRUE;
  // Then we set this attribute here so that olivero tab.js applies the
  // responsiveness script on the tabs.
  $variables['tab_nav_tag_attributes']['data-drupal-nav-primary-tabs'] = TRUE;

  $variables['#attached']['library'][] = 'views_attachment_tabs_olivero/tabs';
  $variables['tab_navigations_attributes']['class'][] = 'tabs';
  $variables['tab_navigations_attributes']['class'][] = 'tabs--primary';
  foreach ($variables['tab_navigations'] as $index => &$tab_navigation) {
    $id = $tab_navigation['unique_id'];
    $tab_id = Html::getId($id . '--tab-nav--' . $index);
    $panel_id = Html::getId($id . '--tab-panel--' . $index);

    $tab_navigation['wrapper_attributes']['class'][] = 'tabs__tab';
    $tab_navigation['content']['#attributes']['class'][] = 'tabs__link js-tabs-link';
    $tab_navigation['content']['#attributes']['id'] = $tab_id;
    $tab_navigation['content']['#attributes']['aria-controls'] = $panel_id;
    $variables['tab_panels'][$index]['wrapper_attributes']['aria-labelledby'] = $tab_id;
    $variables['tab_panels'][$index]['wrapper_attributes']['id'] = $panel_id;

    if (empty($tab_navigation['is_first_tab'])) {
      $tab_navigation['content']['#attributes']['aria-selected'] = 'false';
      $variables['tab_panels'][$index]['wrapper_attributes']['hidden'] = TRUE;
      continue;
    }

    // Setting the first tab as active.
    $tab_navigation['wrapper_attributes']['class'][] = 'is-active';
    $tab_navigation['content']['#attributes']['class'][] = 'is-active';
    $tab_navigation['content']['#attributes']['aria-selected'] = 'true';
    // Adding another button for mobile integration with olivero.
    $tab_button = $tab_navigation['content'];
    $tab_navigation['content'] = [
      'tab_button' => $tab_button,
      'tab_trigger_olivero' => [
        '#type' => 'html_tag',
        '#tag' => 'button',
        '#attributes' => [
          'class' => ['tabs__trigger'],
          'aria-label' => t('Tabs display toggle'),
          'aria-expanded' => 'false',
        ],
        'icon' => [
          '#type' => 'html_tag',
          '#tag' => 'span',
          '#attributes' => ['class' => ['tabs__trigger-icon']],
          'span1' => [
            '#type' => 'html_tag',
            '#tag' => 'span',
          ],
          'span2' => [
            '#type' => 'html_tag',
            '#tag' => 'span',
          ],
          'span3' => [
            '#type' => 'html_tag',
            '#tag' => 'span',
          ],
        ],
      ],
    ];
  }
}

/**
 * Checks if olivero theme is activated or it's a base theme.
 *
 * @return bool
 *   True when active, False otherwise.
 */
function _views_attachment_tabs_olivero_theme_is_activated(): bool {
  $active_theme = \Drupal::service('theme.manager')->getActiveTheme();
  if ($active_theme->getName() === 'olivero') {
    return TRUE;
  }

  foreach ($active_theme->getBaseThemeExtensions() as $base_theme) {
    if ($base_theme->getName() === 'olivero') {
      return TRUE;
    }
  }

  return FALSE;
}
